version: "3"
services:
  postgres:
    image: 'postgres'
    container_name: 'psql'
    environment:
      - 'POSTGRES_DB=Mobile'
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD=pin@#1358'
      - TZ='Asia/Almaty'
  app:
    build: ./
    container_name: 'crud'
    ports:
      - 8080:8080